files:
  - source: '/unicenta-opos/src/main/resources/**/*.properties'
    ignore:
      - liquibase.properties
    translation: '/unicenta-opos/src/main/resources/**/%file_name%_%two_letters_code%.%file_extension%'
